# Jekyll configuration

name: Wouter Bauchart
title: Wouter Bauchart
description: Cloud solutions

# Url is currently only used only for the RSS feed in feed.xml
url: http://bauchart.be
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: Wouter Bauchart
copyright: 

share:
  facebook: true
  twitter: true
  gplus: false
  linkedin: true
  pinterest: false
  email: true

social:
  github: WouterBau
  stackoverflow: '10890619'
  linkedin: 'wouter-bauchart-63a26519'
  instagram: ''
  lastfm: 'Freakyio'
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 
comments: false

permalink: /:year/:month/:day/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
paginate: 5

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
